language: python
matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "3.4"
      env: TOX_ENV=py34
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.6"
      env: TOX_ENV=py36
sudo: false
install:
- pip install tox
script: tox -e $TOX_ENV
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "0sE28PzKVwxpPkb/8CPvGcqVs/VFY5i2fWxAdKrgHgKFO0eMEQo+jjCvILRJb3zQ9RBDd5J9s2i1O2qtI5PW+iNuhSwpbnap7eRTYo27dZZOfElMYjkivF0Wl2yHTIYhk5W+LSM9iL9n2RgdEZMiXhGpFB5ti4Ozsj0P21Vx1wp/K+WOFtyxdu2fAJKNS7GWkOWYHiw93mPqcpqryvE4DVN3tauSKTaPGT5ITt85EqO7rrWC0LyaLqdl0O+pwLCdbMeoon+OASsqQNr+Ey85uiQZXrmXHMqJJU5f1Qde2YZAtJdbXpWvA8VBxmvmuQBIRG5ASWYjDSboygTG6A9kWQAuko8Py2ZwtMpdH2vpGcJ+v55tBo5u67m5pa0zNBVFyxx2TpH5T1QKAXTACdEFcUbfLNNL3T7holZeMrXyQHULfTHe5z6luuqDPFiivaV3KRuLSz3ScMy+nl9DPQh/vVyjErJu81un6xgVnhp8iBI5YVSPxWsVnsksyWczIs0F1iUe5BJttKFHAG25wpy52y9hZq5Iu4sT1HTE6/cT413e3mcxgcfrlG1ZrwgnJ4kIEyUni+MaXoL4ZITb1/XGum3S9oC2DHz6yyEeudrTr8JxlQbG9pDx4HSb6uxdDNNMpagLqixdPGEGENHbwBTlf7DlqlhY/h21keBeF1AqLPA="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: google/pyu2f
